---
- name: install Docker
  hosts: localhost
  become: true
  tasks:
    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise
          Linux') else (ansible_distribution | lower) }}"
    - name: Add signing key
      ansible.builtin.rpm_key:
        key: https://download.docker.com/linux/{{ mydistribution }}/gpg
        state: present
    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: https://download.docker.com/linux/{{ mydistribution
          }}/$releasever/$basearch/stable
        enabled: true
        gpgcheck: true
        gpgkey: https://download.docker.com/linux/{{ mydistribution }}/gpg
    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
    - name: Start Docker
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started
    - name: pull httpd image
      docker_image:
        name: httpd
        state: present
    - name: Creating Directory
      file:
        path: /web
        state: directory
    - name: copy content
      copy:
        src: myweb.html
        dest: /web/myweb.html
    - name: Launch docker container
      docker_container:
        name: Dockerwebserver
        image: httpd
        state: started
        exposed_ports: "80"
        ports: 8081:80
        volumes: /web/:/usr/local/apache2/htdocs/
